name: Deploy React App to S3

on:
  workflow_call:
    inputs:
      s3_bucket:
        required: true
        type: string
      repo:
        required: true
        type: string
      branch:
        required: false
        type: string
        default: "main"

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout react repository for build
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repo }}
          ref: ${{ inputs.branch }}

      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      - run: npm ci
      - run: npm run build

      - name: Deploy to s3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 sync ./build s3://${{ inputs.s3_bucket }} --delete --region us-west-2 --debug

